# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true

# Configure Gradle to use Android Studio's bundled JDK (Java 21)
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
